Sync Notion page with geo_autoscan_library.yaml
bio-learn/biolearn pull request #113
Opened 2024-12-11 05:10 UTC by mtc1386

2024-12-21 14:12 UTC, mtc1386 commented
We should add `NOTION_TOKEN` and `NOTION_SERIES_DATABASE_ID` as project secrets for GitHub Actions.

Since the Notion API doesn’t support updating certain database object properties, the script cannot handle an empty schema database. I recommend creating an empty page with the required properties and then deleting it. This way, we can define the database schema.


>    AgePresent: Select
>     SexPresent: Select
>     Link: URL
>     Platform: Multi-Select
>     Samples: Number
>     Tags: Multi-Select
>     Title: Text

2025-01-04 23:30 UTC, sarudak requested changes
In trying to do local testing I am am having issues where it will populate a few entries and then crash with a 409 Conflict status. Perhaps something is wrong with the async? It does add a few more rows each time I run it.

Note that "python-dotenv" and "notion-client" need to be added as dev dependencies for the script to work.

2025-01-04 23:30 UTC, sarudak commented on scripts/sync_library_entry_to_notion.py
> +def get_data_to_update_in_notoin(
notoin -> notion

2025-01-04 23:30 UTC, sarudak commented on scripts/sync_library_entry_to_notion.py
> +            f"Local item id {local_item.id} does not match remote item id {
The interpolation being broken across lines caused an error for me.

2025-01-09 21:54 UTC, sarudak approved these changes
Works now

2025-01-09 21:54 UTC, merged